development:
  environment: "sandbox"
  username: "gprathuis-facilitator_api1.gmail.com"
  password: "KPEHFDPTXTXD2ELL"
  signature: "AJKFknKyXBVAvenGc1RJ96CSeZWMA4lFcjjQsfiaiKcdghqjSwxLgIPu"
  application_id: "APP-80W284485P519543T"